/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_win_glk_objects (void) PRIVATE;
GtkWidget* create_gglk_win (void) PRIVATE;
GtkWidget* create_dialog_prefs (void) PRIVATE;
GtkWidget* create_dialog_about (void) PRIVATE;
GtkWidget* create_dialog_gestalt (void) PRIVATE;
GtkWidget* create_dialog_styles (void) PRIVATE;
