/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_win_glk_objects (void)
{
  GtkWidget *win_glk_objects;
  GtkWidget *table1;
  GtkWidget *glabel1;
  GtkWidget *object_ID;
  GtkWidget *glabel2;
  GtkObject *rock_adj;
  GtkWidget *rock;
  GtkWidget *glabel3;
  GtkObject *disprock_adj;
  GtkWidget *disprock;
  GtkWidget *notebook1;
  GtkWidget *table2;
  GtkWidget *method_above;
  GSList *method_above_group = NULL;
  GtkWidget *method_fixed;
  GtkWidget *method_left;
  GtkWidget *glabel4;
  GtkWidget *glabel5;
  GtkObject *size_adj;
  GtkWidget *size;
  GtkWidget *method_below;
  GtkWidget *method_right;
  GtkWidget *drawingarea1;
  GtkWidget *label65;
  GtkWidget *table8;
  GtkWidget *request_char;
  GtkWidget *request_line;
  GtkWidget *request_mouse;
  GtkWidget *request_hyper;
  GtkWidget *emit_char;
  GtkWidget *emit_line;
  GtkWidget *emit_mouse;
  GtkWidget *emit_hyper;
  GtkObject *val2_mouse_adj;
  GtkWidget *val2_mouse;
  GtkWidget *request_arrange;
  GtkWidget *request_redraw;
  GtkWidget *emit_arrange;
  GtkWidget *emit_redraw;
  GtkObject *val1_mouse_adj;
  GtkWidget *val1_mouse;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *name_char;
  GtkObject *val1_char_adj;
  GtkWidget *val1_char;
  GtkWidget *label115;
  GtkWidget *string_line;
  GtkWidget *label116;
  GtkWidget *label109;
  GtkObject *val1_hyper_adj;
  GtkWidget *val1_hyper;
  GtkWidget *label44;
  GtkWidget *framed;
  GtkWidget *label69;
  GtkWidget *table3;
  GtkWidget *str_fmode_WriteAppend;
  GSList *str_fmode_WriteAppend_group = NULL;
  GtkWidget *str_fmode_ReadWrite;
  GtkWidget *str_fmode_Write;
  GtkWidget *str_fmode_Read;
  GtkWidget *glabel6;
  GtkWidget *glabel7;
  GtkWidget *glabel8;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview1;
  GtkObject *index_adj;
  GtkWidget *index;
  GtkObject *length_adj;
  GtkWidget *length;
  GtkObject *read_count_adj;
  GtkWidget *read_count;
  GtkObject *write_count_adj;
  GtkWidget *write_count;
  GtkWidget *label66;
  GtkWidget *table4;
  GtkWidget *filename;
  GtkWidget *fmode_ReadWrite;
  GSList *fmode_ReadWrite_group = NULL;
  GtkWidget *fmode_WriteAppend;
  GtkWidget *fmode_Read;
  GtkWidget *fmode_Write;
  GtkWidget *usage_Transcript;
  GSList *usage_Transcript_group = NULL;
  GtkWidget *usage_InputRecord;
  GtkWidget *usage_Data;
  GtkWidget *usage_SavedGame;
  GtkWidget *usage_Text;
  GtkWidget *glabel9;
  GtkWidget *glabel10;
  GtkWidget *glabel11;
  GtkWidget *label67;
  GtkWidget *table5;
  GtkObject *volume_adj;
  GtkWidget *volume;
  GtkObject *repeats_adj;
  GtkWidget *repeats;
  GtkObject *sound_adj;
  GtkWidget *sound;
  GtkObject *notify_adj;
  GtkWidget *notify;
  GtkWidget *glabel12;
  GtkWidget *glabel13;
  GtkWidget *glabel14;
  GtkWidget *glabel15;
  GtkWidget *label68;
  GtkWidget *hbuttonbox5;
  GtkWidget *button19;
  GtkWidget *hseparator9;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;

  win_glk_objects = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (win_glk_objects), "Glk Object Browser");

  table1 = gtk_table_new (6, 3, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (win_glk_objects), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 6);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 6);

  glabel1 = gtk_label_new ("ID:");
  gtk_widget_show (glabel1);
  gtk_table_attach (GTK_TABLE (table1), glabel1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel1), 0, 0.5);

  object_ID = gtk_label_new ("");
  gtk_widget_show (object_ID);
  gtk_table_attach (GTK_TABLE (table1), object_ID, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (object_ID), 0, 0.5);

  glabel2 = gtk_label_new_with_mnemonic ("_Rock:");
  gtk_widget_show (glabel2);
  gtk_table_attach (GTK_TABLE (table1), glabel2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel2), 0, 0.5);

  rock_adj = gtk_adjustment_new (1, 0, 4.29497e+09, 1, 10, 10);
  rock = gtk_spin_button_new (GTK_ADJUSTMENT (rock_adj), 1, 0);
  gtk_widget_show (rock);
  gtk_table_attach (GTK_TABLE (table1), rock, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (rock), TRUE);

  glabel3 = gtk_label_new_with_mnemonic ("_Disprock:");
  gtk_widget_show (glabel3);
  gtk_table_attach (GTK_TABLE (table1), glabel3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel3), 0, 0.5);

  disprock_adj = gtk_adjustment_new (1, 0, 4.29497e+09, 1, 10, 10);
  disprock = gtk_spin_button_new (GTK_ADJUSTMENT (disprock_adj), 1, 0);
  gtk_widget_show (disprock);
  gtk_table_attach (GTK_TABLE (table1), disprock, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (disprock), TRUE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_table_attach (GTK_TABLE (table1), notebook1, 1, 3, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (notebook1, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (notebook1), FALSE);
  gtk_notebook_set_show_border (GTK_NOTEBOOK (notebook1), FALSE);

  table2 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook1), table2);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), table2,
                                      TRUE, TRUE, GTK_PACK_START);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 6);

  method_above = gtk_radio_button_new_with_mnemonic (NULL, "Above");
  gtk_widget_show (method_above);
  gtk_table_attach (GTK_TABLE (table2), method_above, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (method_above), method_above_group);
  method_above_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (method_above));

  method_fixed = gtk_check_button_new_with_mnemonic ("Fixed");
  gtk_widget_show (method_fixed);
  gtk_table_attach (GTK_TABLE (table2), method_fixed, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  method_left = gtk_radio_button_new_with_mnemonic (NULL, "Left");
  gtk_widget_show (method_left);
  gtk_table_attach (GTK_TABLE (table2), method_left, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (method_left), method_above_group);
  method_above_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (method_left));

  glabel4 = gtk_label_new ("Direction:");
  gtk_widget_show (glabel4);
  gtk_table_attach (GTK_TABLE (table2), glabel4, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel4), 0, 0.5);

  glabel5 = gtk_label_new ("Size:");
  gtk_widget_show (glabel5);
  gtk_table_attach (GTK_TABLE (table2), glabel5, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel5), 0, 0.5);

  size_adj = gtk_adjustment_new (1, 0, 10000, 1, 10, 10);
  size = gtk_spin_button_new (GTK_ADJUSTMENT (size_adj), 1, 0);
  gtk_widget_show (size);
  gtk_table_attach (GTK_TABLE (table2), size, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  method_below = gtk_radio_button_new_with_mnemonic (NULL, "Below");
  gtk_widget_show (method_below);
  gtk_table_attach (GTK_TABLE (table2), method_below, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (method_below), method_above_group);
  method_above_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (method_below));

  method_right = gtk_radio_button_new_with_mnemonic (NULL, "Right");
  gtk_widget_show (method_right);
  gtk_table_attach (GTK_TABLE (table2), method_right, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (method_right), method_above_group);
  method_above_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (method_right));

  drawingarea1 = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea1);
  gtk_table_attach (GTK_TABLE (table2), drawingarea1, 0, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label65 = gtk_label_new ("");
  gtk_widget_show (label65);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label65);

  table8 = gtk_table_new (8, 6, FALSE);
  gtk_widget_show (table8);
  gtk_container_add (GTK_CONTAINER (notebook1), table8);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 6);

  request_char = gtk_check_button_new_with_mnemonic ("_Character");
  gtk_widget_show (request_char);
  gtk_table_attach (GTK_TABLE (table8), request_char, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  request_line = gtk_check_button_new_with_mnemonic ("_Line");
  gtk_widget_show (request_line);
  gtk_table_attach (GTK_TABLE (table8), request_line, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  request_mouse = gtk_check_button_new_with_mnemonic ("_Mouse");
  gtk_widget_show (request_mouse);
  gtk_table_attach (GTK_TABLE (table8), request_mouse, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  request_hyper = gtk_check_button_new_with_mnemonic ("_Hyperlink");
  gtk_widget_show (request_hyper);
  gtk_table_attach (GTK_TABLE (table8), request_hyper, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  emit_char = gtk_button_new_with_mnemonic ("emit:");
  gtk_widget_show (emit_char);
  gtk_table_attach (GTK_TABLE (table8), emit_char, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  emit_line = gtk_button_new_with_mnemonic ("emit:");
  gtk_widget_show (emit_line);
  gtk_table_attach (GTK_TABLE (table8), emit_line, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  emit_mouse = gtk_button_new_with_mnemonic ("emit:");
  gtk_widget_show (emit_mouse);
  gtk_table_attach (GTK_TABLE (table8), emit_mouse, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  emit_hyper = gtk_button_new_with_mnemonic ("emit:");
  gtk_widget_show (emit_hyper);
  gtk_table_attach (GTK_TABLE (table8), emit_hyper, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  val2_mouse_adj = gtk_adjustment_new (0, 0, 1000, 1, 10, 10);
  val2_mouse = gtk_spin_button_new (GTK_ADJUSTMENT (val2_mouse_adj), 1, 0);
  gtk_widget_show (val2_mouse);
  gtk_table_attach (GTK_TABLE (table8), val2_mouse, 5, 6, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (val2_mouse), TRUE);

  request_arrange = gtk_check_button_new_with_mnemonic ("_Arrange");
  gtk_widget_show (request_arrange);
  gtk_table_attach (GTK_TABLE (table8), request_arrange, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (request_arrange, GTK_CAN_FOCUS);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (request_arrange), TRUE);

  request_redraw = gtk_check_button_new_with_mnemonic ("Redra_w");
  gtk_widget_show (request_redraw);
  gtk_table_attach (GTK_TABLE (table8), request_redraw, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (request_redraw, GTK_CAN_FOCUS);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (request_redraw), TRUE);

  emit_arrange = gtk_button_new_with_mnemonic ("emit");
  gtk_widget_show (emit_arrange);
  gtk_table_attach (GTK_TABLE (table8), emit_arrange, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  emit_redraw = gtk_button_new_with_mnemonic ("emit");
  gtk_widget_show (emit_redraw);
  gtk_table_attach (GTK_TABLE (table8), emit_redraw, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  val1_mouse_adj = gtk_adjustment_new (0, 0, 1000, 1, 10, 10);
  val1_mouse = gtk_spin_button_new (GTK_ADJUSTMENT (val1_mouse_adj), 1, 0);
  gtk_widget_show (val1_mouse);
  gtk_table_attach (GTK_TABLE (table8), val1_mouse, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (val1_mouse), TRUE);

  label107 = gtk_label_new_with_mnemonic ("_x:");
  gtk_widget_show (label107);
  gtk_table_attach (GTK_TABLE (table8), label107, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label107), 0, 0.5);

  label108 = gtk_label_new_with_mnemonic ("_y:");
  gtk_widget_show (label108);
  gtk_table_attach (GTK_TABLE (table8), label108, 4, 5, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label108), 0, 0.5);

  name_char = gtk_label_new ("(space)");
  gtk_widget_show (name_char);
  gtk_table_attach (GTK_TABLE (table8), name_char, 4, 6, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (name_char), 0, 0.5);

  val1_char_adj = gtk_adjustment_new (32, -28, 255, 1, 10, 10);
  val1_char = gtk_spin_button_new (GTK_ADJUSTMENT (val1_char_adj), 1, 0);
  gtk_widget_show (val1_char);
  gtk_table_attach (GTK_TABLE (table8), val1_char, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (val1_char), TRUE);

  label115 = gtk_label_new ("char:");
  gtk_widget_show (label115);
  gtk_table_attach (GTK_TABLE (table8), label115, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label115), 0, 0.5);

  string_line = gtk_entry_new ();
  gtk_widget_show (string_line);
  gtk_table_attach (GTK_TABLE (table8), string_line, 3, 6, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label116 = gtk_label_new ("text:");
  gtk_widget_show (label116);
  gtk_table_attach (GTK_TABLE (table8), label116, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label116), 0, 0.5);

  label109 = gtk_label_new_with_mnemonic ("_num:");
  gtk_widget_show (label109);
  gtk_table_attach (GTK_TABLE (table8), label109, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  val1_hyper_adj = gtk_adjustment_new (0, 0, 1000, 1, 10, 10);
  val1_hyper = gtk_spin_button_new (GTK_ADJUSTMENT (val1_hyper_adj), 1, 0);
  gtk_widget_show (val1_hyper);
  gtk_table_attach (GTK_TABLE (table8), val1_hyper, 3, 6, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (val1_hyper), TRUE);

  label44 = gtk_label_new ("<b>Requested Glk events:</b>");
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table8), label44, 0, 6, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);

  framed = gtk_check_button_new_with_mnemonic ("_Framed");
  gtk_widget_show (framed);
  gtk_table_attach (GTK_TABLE (table8), framed, 0, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label69 = gtk_label_new ("");
  gtk_widget_show (label69);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label69);

  table3 = gtk_table_new (5, 3, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (notebook1), table3);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 6);

  str_fmode_WriteAppend = gtk_radio_button_new_with_mnemonic (NULL, "WriteAppend");
  gtk_widget_show (str_fmode_WriteAppend);
  gtk_table_attach (GTK_TABLE (table3), str_fmode_WriteAppend, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (str_fmode_WriteAppend), str_fmode_WriteAppend_group);
  str_fmode_WriteAppend_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (str_fmode_WriteAppend));

  str_fmode_ReadWrite = gtk_radio_button_new_with_mnemonic (NULL, "ReadWrite");
  gtk_widget_show (str_fmode_ReadWrite);
  gtk_table_attach (GTK_TABLE (table3), str_fmode_ReadWrite, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (str_fmode_ReadWrite), str_fmode_WriteAppend_group);
  str_fmode_WriteAppend_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (str_fmode_ReadWrite));

  str_fmode_Write = gtk_radio_button_new_with_mnemonic (NULL, "Write");
  gtk_widget_show (str_fmode_Write);
  gtk_table_attach (GTK_TABLE (table3), str_fmode_Write, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (str_fmode_Write), str_fmode_WriteAppend_group);
  str_fmode_WriteAppend_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (str_fmode_Write));

  str_fmode_Read = gtk_radio_button_new_with_mnemonic (NULL, "Read");
  gtk_widget_show (str_fmode_Read);
  gtk_table_attach (GTK_TABLE (table3), str_fmode_Read, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (str_fmode_Read), str_fmode_WriteAppend_group);
  str_fmode_WriteAppend_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (str_fmode_Read));

  glabel6 = gtk_label_new_with_mnemonic ("f_mode:");
  gtk_widget_show (glabel6);
  gtk_table_attach (GTK_TABLE (table3), glabel6, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel6), 0, 0.5);

  glabel7 = gtk_label_new_with_mnemonic ("Reads / Writes:");
  gtk_widget_show (glabel7);
  gtk_table_attach (GTK_TABLE (table3), glabel7, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel7), 0, 0.5);

  glabel8 = gtk_label_new_with_mnemonic ("Index / Length:");
  gtk_widget_show (glabel8);
  gtk_table_attach (GTK_TABLE (table3), glabel8, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel8), 0, 0.5);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_table_attach (GTK_TABLE (table3), scrolledwindow3, 0, 3, 4, 5,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_ETCHED_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview1);
  gtk_widget_set_size_request (textview1, 30, 30);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview1), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview1), FALSE);

  index_adj = gtk_adjustment_new (0, 0, 1e+12, 1, 10, 10);
  index = gtk_spin_button_new (GTK_ADJUSTMENT (index_adj), 1, 0);
  gtk_widget_show (index);
  gtk_table_attach (GTK_TABLE (table3), index, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (index), TRUE);

  length_adj = gtk_adjustment_new (0, -1, 1e+12, 1, 10, 10);
  length = gtk_spin_button_new (GTK_ADJUSTMENT (length_adj), 1, 0);
  gtk_widget_show (length);
  gtk_table_attach (GTK_TABLE (table3), length, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (length), TRUE);

  read_count_adj = gtk_adjustment_new (0, 0, 1e+12, 1, 10, 10);
  read_count = gtk_spin_button_new (GTK_ADJUSTMENT (read_count_adj), 1, 0);
  gtk_widget_show (read_count);
  gtk_table_attach (GTK_TABLE (table3), read_count, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (read_count), TRUE);

  write_count_adj = gtk_adjustment_new (0, 0, 1e+12, 1, 10, 10);
  write_count = gtk_spin_button_new (GTK_ADJUSTMENT (write_count_adj), 1, 0);
  gtk_widget_show (write_count);
  gtk_table_attach (GTK_TABLE (table3), write_count, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (write_count), TRUE);

  label66 = gtk_label_new ("");
  gtk_widget_show (label66);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label66);

  table4 = gtk_table_new (6, 3, FALSE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (notebook1), table4);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 6);

  filename = gtk_entry_new ();
  gtk_widget_show (filename);
  gtk_table_attach (GTK_TABLE (table4), filename, 1, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  fmode_ReadWrite = gtk_radio_button_new_with_mnemonic (NULL, "ReadWrite");
  gtk_widget_show (fmode_ReadWrite);
  gtk_table_attach (GTK_TABLE (table4), fmode_ReadWrite, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (fmode_ReadWrite), fmode_ReadWrite_group);
  fmode_ReadWrite_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (fmode_ReadWrite));

  fmode_WriteAppend = gtk_radio_button_new_with_mnemonic (NULL, "WriteAppend");
  gtk_widget_show (fmode_WriteAppend);
  gtk_table_attach (GTK_TABLE (table4), fmode_WriteAppend, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (fmode_WriteAppend), fmode_ReadWrite_group);
  fmode_ReadWrite_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (fmode_WriteAppend));

  fmode_Read = gtk_radio_button_new_with_mnemonic (NULL, "Read");
  gtk_widget_show (fmode_Read);
  gtk_table_attach (GTK_TABLE (table4), fmode_Read, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (fmode_Read), fmode_ReadWrite_group);
  fmode_ReadWrite_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (fmode_Read));

  fmode_Write = gtk_radio_button_new_with_mnemonic (NULL, "Write");
  gtk_widget_show (fmode_Write);
  gtk_table_attach (GTK_TABLE (table4), fmode_Write, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (fmode_Write), fmode_ReadWrite_group);
  fmode_ReadWrite_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (fmode_Write));

  usage_Transcript = gtk_radio_button_new_with_mnemonic (NULL, "Transcript");
  gtk_widget_show (usage_Transcript);
  gtk_table_attach (GTK_TABLE (table4), usage_Transcript, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (usage_Transcript), usage_Transcript_group);
  usage_Transcript_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (usage_Transcript));

  usage_InputRecord = gtk_radio_button_new_with_mnemonic (NULL, "InputRecord");
  gtk_widget_show (usage_InputRecord);
  gtk_table_attach (GTK_TABLE (table4), usage_InputRecord, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (usage_InputRecord), usage_Transcript_group);
  usage_Transcript_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (usage_InputRecord));

  usage_Data = gtk_radio_button_new_with_mnemonic (NULL, "Data");
  gtk_widget_show (usage_Data);
  gtk_table_attach (GTK_TABLE (table4), usage_Data, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (usage_Data), usage_Transcript_group);
  usage_Transcript_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (usage_Data));

  usage_SavedGame = gtk_radio_button_new_with_mnemonic (NULL, "SavedGame");
  gtk_widget_show (usage_SavedGame);
  gtk_table_attach (GTK_TABLE (table4), usage_SavedGame, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (usage_SavedGame), usage_Transcript_group);
  usage_Transcript_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (usage_SavedGame));

  usage_Text = gtk_check_button_new_with_mnemonic ("Text");
  gtk_widget_show (usage_Text);
  gtk_table_attach (GTK_TABLE (table4), usage_Text, 1, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  glabel9 = gtk_label_new_with_mnemonic ("_Filename:");
  gtk_widget_show (glabel9);
  gtk_table_attach (GTK_TABLE (table4), glabel9, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel9), 0, 0.5);

  glabel10 = gtk_label_new_with_mnemonic ("f_mode:");
  gtk_widget_show (glabel10);
  gtk_table_attach (GTK_TABLE (table4), glabel10, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel10), 0, 0.5);

  glabel11 = gtk_label_new_with_mnemonic ("_Usage:");
  gtk_widget_show (glabel11);
  gtk_table_attach (GTK_TABLE (table4), glabel11, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel11), 0, 0.5);

  label67 = gtk_label_new ("");
  gtk_widget_show (label67);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label67);

  table5 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (notebook1), table5);
  gtk_table_set_row_spacings (GTK_TABLE (table5), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table5), 6);

  volume_adj = gtk_adjustment_new (1, 0, 65536, 1, 10, 10);
  volume = gtk_spin_button_new (GTK_ADJUSTMENT (volume_adj), 1, 0);
  gtk_widget_show (volume);
  gtk_table_attach (GTK_TABLE (table5), volume, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  repeats_adj = gtk_adjustment_new (1, -1, 1e+12, 1, 10, 10);
  repeats = gtk_spin_button_new (GTK_ADJUSTMENT (repeats_adj), 1, 0);
  gtk_widget_show (repeats);
  gtk_table_attach (GTK_TABLE (table5), repeats, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  sound_adj = gtk_adjustment_new (1, 0, 1e+12, 1, 10, 10);
  sound = gtk_spin_button_new (GTK_ADJUSTMENT (sound_adj), 1, 0);
  gtk_widget_show (sound);
  gtk_table_attach (GTK_TABLE (table5), sound, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  notify_adj = gtk_adjustment_new (1, 0, 1e+12, 1, 10, 10);
  notify = gtk_spin_button_new (GTK_ADJUSTMENT (notify_adj), 1, 0);
  gtk_widget_show (notify);
  gtk_table_attach (GTK_TABLE (table5), notify, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  glabel12 = gtk_label_new_with_mnemonic ("_Sound:");
  gtk_widget_show (glabel12);
  gtk_table_attach (GTK_TABLE (table5), glabel12, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel12), 0, 0.5);

  glabel13 = gtk_label_new_with_mnemonic ("Re_peats:");
  gtk_widget_show (glabel13);
  gtk_table_attach (GTK_TABLE (table5), glabel13, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel13), 0, 0.5);

  glabel14 = gtk_label_new_with_mnemonic ("_Notify:");
  gtk_widget_show (glabel14);
  gtk_table_attach (GTK_TABLE (table5), glabel14, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel14), 0, 0.5);

  glabel15 = gtk_label_new_with_mnemonic ("_Volume:");
  gtk_widget_show (glabel15);
  gtk_table_attach (GTK_TABLE (table5), glabel15, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (glabel15), 0, 0.5);

  label68 = gtk_label_new ("");
  gtk_widget_show (label68);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label68);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox5);
  gtk_table_attach (GTK_TABLE (table1), hbuttonbox5, 0, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox5), GTK_BUTTONBOX_END);

  button19 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button19);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button19);
  GTK_WIDGET_SET_FLAGS (button19, GTK_CAN_DEFAULT);

  hseparator9 = gtk_hseparator_new ();
  gtk_widget_show (hseparator9);
  gtk_table_attach (GTK_TABLE (table1), hseparator9, 1, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_table_attach (GTK_TABLE (table1), scrolledwindow1, 0, 1, 0, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_ETCHED_IN);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview1), FALSE);

  g_signal_connect_swapped ((gpointer) button19, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (win_glk_objects));

  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel2), rock);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel3), disprock);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label107), val1_mouse);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label108), val2_mouse);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label109), val1_hyper);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel6), str_fmode_Read);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel7), read_count);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel8), length);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel9), filename);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel10), fmode_Read);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel11), usage_Text);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel12), sound);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel13), repeats);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel14), notify);
  gtk_label_set_mnemonic_widget (GTK_LABEL (glabel15), volume);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_glk_objects, win_glk_objects, "win_glk_objects");
  GLADE_HOOKUP_OBJECT (win_glk_objects, table1, "table1");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel1, "glabel1");
  GLADE_HOOKUP_OBJECT (win_glk_objects, object_ID, "object_ID");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel2, "glabel2");
  GLADE_HOOKUP_OBJECT (win_glk_objects, rock, "rock");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel3, "glabel3");
  GLADE_HOOKUP_OBJECT (win_glk_objects, disprock, "disprock");
  GLADE_HOOKUP_OBJECT (win_glk_objects, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (win_glk_objects, table2, "table2");
  GLADE_HOOKUP_OBJECT (win_glk_objects, method_above, "method_above");
  GLADE_HOOKUP_OBJECT (win_glk_objects, method_fixed, "method_fixed");
  GLADE_HOOKUP_OBJECT (win_glk_objects, method_left, "method_left");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel4, "glabel4");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel5, "glabel5");
  GLADE_HOOKUP_OBJECT (win_glk_objects, size, "size");
  GLADE_HOOKUP_OBJECT (win_glk_objects, method_below, "method_below");
  GLADE_HOOKUP_OBJECT (win_glk_objects, method_right, "method_right");
  GLADE_HOOKUP_OBJECT (win_glk_objects, drawingarea1, "drawingarea1");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label65, "label65");
  GLADE_HOOKUP_OBJECT (win_glk_objects, table8, "table8");
  GLADE_HOOKUP_OBJECT (win_glk_objects, request_char, "request_char");
  GLADE_HOOKUP_OBJECT (win_glk_objects, request_line, "request_line");
  GLADE_HOOKUP_OBJECT (win_glk_objects, request_mouse, "request_mouse");
  GLADE_HOOKUP_OBJECT (win_glk_objects, request_hyper, "request_hyper");
  GLADE_HOOKUP_OBJECT (win_glk_objects, emit_char, "emit_char");
  GLADE_HOOKUP_OBJECT (win_glk_objects, emit_line, "emit_line");
  GLADE_HOOKUP_OBJECT (win_glk_objects, emit_mouse, "emit_mouse");
  GLADE_HOOKUP_OBJECT (win_glk_objects, emit_hyper, "emit_hyper");
  GLADE_HOOKUP_OBJECT (win_glk_objects, val2_mouse, "val2_mouse");
  GLADE_HOOKUP_OBJECT (win_glk_objects, request_arrange, "request_arrange");
  GLADE_HOOKUP_OBJECT (win_glk_objects, request_redraw, "request_redraw");
  GLADE_HOOKUP_OBJECT (win_glk_objects, emit_arrange, "emit_arrange");
  GLADE_HOOKUP_OBJECT (win_glk_objects, emit_redraw, "emit_redraw");
  GLADE_HOOKUP_OBJECT (win_glk_objects, val1_mouse, "val1_mouse");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label107, "label107");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label108, "label108");
  GLADE_HOOKUP_OBJECT (win_glk_objects, name_char, "name_char");
  GLADE_HOOKUP_OBJECT (win_glk_objects, val1_char, "val1_char");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label115, "label115");
  GLADE_HOOKUP_OBJECT (win_glk_objects, string_line, "string_line");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label116, "label116");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label109, "label109");
  GLADE_HOOKUP_OBJECT (win_glk_objects, val1_hyper, "val1_hyper");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label44, "label44");
  GLADE_HOOKUP_OBJECT (win_glk_objects, framed, "framed");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label69, "label69");
  GLADE_HOOKUP_OBJECT (win_glk_objects, table3, "table3");
  GLADE_HOOKUP_OBJECT (win_glk_objects, str_fmode_WriteAppend, "str_fmode_WriteAppend");
  GLADE_HOOKUP_OBJECT (win_glk_objects, str_fmode_ReadWrite, "str_fmode_ReadWrite");
  GLADE_HOOKUP_OBJECT (win_glk_objects, str_fmode_Write, "str_fmode_Write");
  GLADE_HOOKUP_OBJECT (win_glk_objects, str_fmode_Read, "str_fmode_Read");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel6, "glabel6");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel7, "glabel7");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel8, "glabel8");
  GLADE_HOOKUP_OBJECT (win_glk_objects, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (win_glk_objects, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (win_glk_objects, index, "index");
  GLADE_HOOKUP_OBJECT (win_glk_objects, length, "length");
  GLADE_HOOKUP_OBJECT (win_glk_objects, read_count, "read_count");
  GLADE_HOOKUP_OBJECT (win_glk_objects, write_count, "write_count");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label66, "label66");
  GLADE_HOOKUP_OBJECT (win_glk_objects, table4, "table4");
  GLADE_HOOKUP_OBJECT (win_glk_objects, filename, "filename");
  GLADE_HOOKUP_OBJECT (win_glk_objects, fmode_ReadWrite, "fmode_ReadWrite");
  GLADE_HOOKUP_OBJECT (win_glk_objects, fmode_WriteAppend, "fmode_WriteAppend");
  GLADE_HOOKUP_OBJECT (win_glk_objects, fmode_Read, "fmode_Read");
  GLADE_HOOKUP_OBJECT (win_glk_objects, fmode_Write, "fmode_Write");
  GLADE_HOOKUP_OBJECT (win_glk_objects, usage_Transcript, "usage_Transcript");
  GLADE_HOOKUP_OBJECT (win_glk_objects, usage_InputRecord, "usage_InputRecord");
  GLADE_HOOKUP_OBJECT (win_glk_objects, usage_Data, "usage_Data");
  GLADE_HOOKUP_OBJECT (win_glk_objects, usage_SavedGame, "usage_SavedGame");
  GLADE_HOOKUP_OBJECT (win_glk_objects, usage_Text, "usage_Text");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel9, "glabel9");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel10, "glabel10");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel11, "glabel11");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label67, "label67");
  GLADE_HOOKUP_OBJECT (win_glk_objects, table5, "table5");
  GLADE_HOOKUP_OBJECT (win_glk_objects, volume, "volume");
  GLADE_HOOKUP_OBJECT (win_glk_objects, repeats, "repeats");
  GLADE_HOOKUP_OBJECT (win_glk_objects, sound, "sound");
  GLADE_HOOKUP_OBJECT (win_glk_objects, notify, "notify");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel12, "glabel12");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel13, "glabel13");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel14, "glabel14");
  GLADE_HOOKUP_OBJECT (win_glk_objects, glabel15, "glabel15");
  GLADE_HOOKUP_OBJECT (win_glk_objects, label68, "label68");
  GLADE_HOOKUP_OBJECT (win_glk_objects, hbuttonbox5, "hbuttonbox5");
  GLADE_HOOKUP_OBJECT (win_glk_objects, button19, "button19");
  GLADE_HOOKUP_OBJECT (win_glk_objects, hseparator9, "hseparator9");
  GLADE_HOOKUP_OBJECT (win_glk_objects, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (win_glk_objects, treeview1, "treeview1");

  return win_glk_objects;
}

GtkWidget*
create_gglk_win (void)
{
  GtkWidget *gglk_win;
  GtkWidget *vbox7;
  GtkWidget *menubar;
  GtkWidget *menu_game;
  GtkWidget *menu_game_menu;
  GtkWidget *open;
  GtkWidget *undo;
  GtkWidget *save;
  GtkWidget *separatormenuitem1;
  GtkWidget *restore;
  GtkWidget *image85;
  GtkWidget *restart;
  GtkWidget *image86;
  GtkWidget *quit;
  GtkWidget *menu_edit;
  GtkWidget *menu_edit_menu;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *clear;
  GtkWidget *image87;
  GtkWidget *separator1;
  GtkWidget *input_methods1;
  GtkWidget *menu_glk;
  GtkWidget *menu_glk_menu;
  GtkWidget *styles1;
  GtkWidget *image88;
  GtkWidget *preferences1;
  GtkWidget *objects1;
  GtkWidget *image89;
  GtkWidget *gestalt1;
  GtkWidget *image90;
  GtkWidget *gglk_root;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  gglk_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gglk_win), "GtkGlk");

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (gglk_win), vbox7);

  menubar = gtk_menu_bar_new ();
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox7), menubar, FALSE, FALSE, 0);

  menu_game = gtk_menu_item_new_with_mnemonic ("_Game");
  gtk_widget_show (menu_game);
  gtk_container_add (GTK_CONTAINER (menubar), menu_game);

  menu_game_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menu_game), menu_game_menu);

  open = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open);
  gtk_container_add (GTK_CONTAINER (menu_game_menu), open);

  undo = gtk_image_menu_item_new_from_stock ("gtk-undo", accel_group);
  gtk_widget_show (undo);
  gtk_container_add (GTK_CONTAINER (menu_game_menu), undo);

  save = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save);
  gtk_container_add (GTK_CONTAINER (menu_game_menu), save);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu_game_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  restore = gtk_image_menu_item_new_with_mnemonic ("_Restore");
  gtk_widget_show (restore);
  gtk_container_add (GTK_CONTAINER (menu_game_menu), restore);

  image85 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image85);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (restore), image85);

  restart = gtk_image_menu_item_new_with_mnemonic ("Restar_t");
  gtk_widget_show (restart);
  gtk_container_add (GTK_CONTAINER (menu_game_menu), restart);

  image86 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image86);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (restart), image86);

  quit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (menu_game_menu), quit);

  menu_edit = gtk_menu_item_new_with_mnemonic ("_Edit");
  gtk_widget_show (menu_edit);
  gtk_container_add (GTK_CONTAINER (menubar), menu_edit);

  menu_edit_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menu_edit), menu_edit_menu);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menu_edit_menu), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menu_edit_menu), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menu_edit_menu), paste1);

  clear = gtk_image_menu_item_new_with_mnemonic ("Clea_r");
  gtk_widget_show (clear);
  gtk_container_add (GTK_CONTAINER (menu_edit_menu), clear);

  image87 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image87);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (clear), image87);

  separator1 = gtk_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (menu_edit_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  input_methods1 = gtk_menu_item_new_with_mnemonic ("Input _Methods");
  gtk_widget_show (input_methods1);
  gtk_container_add (GTK_CONTAINER (menu_edit_menu), input_methods1);

  menu_glk = gtk_menu_item_new_with_mnemonic ("Gl_k");
  gtk_widget_show (menu_glk);
  gtk_container_add (GTK_CONTAINER (menubar), menu_glk);

  menu_glk_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menu_glk), menu_glk_menu);

  styles1 = gtk_image_menu_item_new_with_mnemonic ("_Styles");
  gtk_widget_show (styles1);
  gtk_container_add (GTK_CONTAINER (menu_glk_menu), styles1);

  image88 = gtk_image_new_from_stock ("gtk-select-font", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image88);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (styles1), image88);

  preferences1 = gtk_image_menu_item_new_from_stock ("gtk-preferences", accel_group);
  gtk_widget_show (preferences1);
  gtk_container_add (GTK_CONTAINER (menu_glk_menu), preferences1);

  objects1 = gtk_image_menu_item_new_with_mnemonic ("_Objects");
  gtk_widget_show (objects1);
  gtk_container_add (GTK_CONTAINER (menu_glk_menu), objects1);

  image89 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image89);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (objects1), image89);

  gestalt1 = gtk_image_menu_item_new_with_mnemonic ("_Gestalt");
  gtk_widget_show (gestalt1);
  gtk_container_add (GTK_CONTAINER (menu_glk_menu), gestalt1);

  image90 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image90);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (gestalt1), image90);

  gglk_root = gtk_event_box_new ();
  gtk_widget_show (gglk_root);
  gtk_box_pack_start (GTK_BOX (vbox7), gglk_root, TRUE, TRUE, 0);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox7), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) menu_game, "activate",
                    G_CALLBACK (on_game_menu_activate),
                    NULL);
  g_signal_connect ((gpointer) open, "activate",
                    G_CALLBACK (on_open_activate),
                    NULL);
  g_signal_connect ((gpointer) undo, "activate",
                    G_CALLBACK (on_undo_activate),
                    NULL);
  g_signal_connect ((gpointer) save, "activate",
                    G_CALLBACK (on_save_activate),
                    NULL);
  g_signal_connect ((gpointer) restore, "activate",
                    G_CALLBACK (on_restore_activate),
                    NULL);
  g_signal_connect ((gpointer) restart, "activate",
                    G_CALLBACK (on_restart_activate),
                    NULL);
  g_signal_connect ((gpointer) quit, "activate",
                    G_CALLBACK (on_quit_activate),
                    NULL);
  g_signal_connect ((gpointer) menu_edit, "activate",
                    G_CALLBACK (on_edit_menu_activate),
                    NULL);
  g_signal_connect ((gpointer) cut1, "activate",
                    G_CALLBACK (menu_cut),
                    NULL);
  g_signal_connect ((gpointer) copy1, "activate",
                    G_CALLBACK (menu_copy),
                    NULL);
  g_signal_connect ((gpointer) paste1, "activate",
                    G_CALLBACK (menu_paste),
                    NULL);
  g_signal_connect ((gpointer) clear, "activate",
                    G_CALLBACK (on_clear_activate),
                    NULL);
  g_signal_connect ((gpointer) styles1, "activate",
                    G_CALLBACK (menu_styles),
                    NULL);
  g_signal_connect ((gpointer) preferences1, "activate",
                    G_CALLBACK (menu_preferences),
                    NULL);
  g_signal_connect ((gpointer) objects1, "activate",
                    G_CALLBACK (menu_objects),
                    NULL);
  g_signal_connect ((gpointer) gestalt1, "activate",
                    G_CALLBACK (menu_gestalt),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gglk_win, gglk_win, "gglk_win");
  GLADE_HOOKUP_OBJECT (gglk_win, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (gglk_win, menubar, "menubar");
  GLADE_HOOKUP_OBJECT (gglk_win, menu_game, "menu_game");
  GLADE_HOOKUP_OBJECT (gglk_win, menu_game_menu, "menu_game_menu");
  GLADE_HOOKUP_OBJECT (gglk_win, open, "open");
  GLADE_HOOKUP_OBJECT (gglk_win, undo, "undo");
  GLADE_HOOKUP_OBJECT (gglk_win, save, "save");
  GLADE_HOOKUP_OBJECT (gglk_win, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (gglk_win, restore, "restore");
  GLADE_HOOKUP_OBJECT (gglk_win, image85, "image85");
  GLADE_HOOKUP_OBJECT (gglk_win, restart, "restart");
  GLADE_HOOKUP_OBJECT (gglk_win, image86, "image86");
  GLADE_HOOKUP_OBJECT (gglk_win, quit, "quit");
  GLADE_HOOKUP_OBJECT (gglk_win, menu_edit, "menu_edit");
  GLADE_HOOKUP_OBJECT (gglk_win, menu_edit_menu, "menu_edit_menu");
  GLADE_HOOKUP_OBJECT (gglk_win, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (gglk_win, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (gglk_win, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (gglk_win, clear, "clear");
  GLADE_HOOKUP_OBJECT (gglk_win, image87, "image87");
  GLADE_HOOKUP_OBJECT (gglk_win, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (gglk_win, input_methods1, "input_methods1");
  GLADE_HOOKUP_OBJECT (gglk_win, menu_glk, "menu_glk");
  GLADE_HOOKUP_OBJECT (gglk_win, menu_glk_menu, "menu_glk_menu");
  GLADE_HOOKUP_OBJECT (gglk_win, styles1, "styles1");
  GLADE_HOOKUP_OBJECT (gglk_win, image88, "image88");
  GLADE_HOOKUP_OBJECT (gglk_win, preferences1, "preferences1");
  GLADE_HOOKUP_OBJECT (gglk_win, objects1, "objects1");
  GLADE_HOOKUP_OBJECT (gglk_win, image89, "image89");
  GLADE_HOOKUP_OBJECT (gglk_win, gestalt1, "gestalt1");
  GLADE_HOOKUP_OBJECT (gglk_win, image90, "image90");
  GLADE_HOOKUP_OBJECT (gglk_win, gglk_root, "gglk_root");
  GLADE_HOOKUP_OBJECT (gglk_win, statusbar, "statusbar");

  gtk_window_add_accel_group (GTK_WINDOW (gglk_win), accel_group);

  return gglk_win;
}

GtkWidget*
create_dialog_prefs (void)
{
  GtkWidget *dialog_prefs;
  GtkWidget *dialog_vbox1;
  GtkWidget *frame2;
  GtkWidget *vbox6;
  GtkWidget *showmenu;
  GtkWidget *showstatusbar;
  GtkWidget *checkbutton4;
  GtkWidget *usescrollbars;
  GtkWidget *label105;
  GtkWidget *frame3;
  GtkWidget *hbox8;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *label106;
  GtkWidget *dialog_action_area1;
  GtkWidget *button20;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  dialog_prefs = gtk_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (dialog_prefs), 6);
  gtk_window_set_title (GTK_WINDOW (dialog_prefs), "GtkGlk Preferences");
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_prefs), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog_prefs)->vbox;
  gtk_widget_show (dialog_vbox1);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), frame2, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_NONE);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (frame2), vbox6);
  gtk_container_set_border_width (GTK_CONTAINER (vbox6), 12);

  showmenu = gtk_check_button_new_with_mnemonic ("Show _Menu");
  gtk_widget_show (showmenu);
  gtk_box_pack_start (GTK_BOX (vbox6), showmenu, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, showmenu, "If you turn the menu off, you can get back here by right-clicking on the application", NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (showmenu), TRUE);

  showstatusbar = gtk_check_button_new_with_mnemonic ("Show _Statusbar");
  gtk_widget_show (showstatusbar);
  gtk_box_pack_start (GTK_BOX (vbox6), showstatusbar, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (showstatusbar), TRUE);

  checkbutton4 = gtk_check_button_new_with_mnemonic ("_Frames around windows");
  gtk_widget_show (checkbutton4);
  gtk_box_pack_start (GTK_BOX (vbox6), checkbutton4, FALSE, FALSE, 0);

  usescrollbars = gtk_check_button_new_with_mnemonic ("Use Scroll_bars");
  gtk_widget_show (usescrollbars);
  gtk_box_pack_start (GTK_BOX (vbox6), usescrollbars, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (usescrollbars), TRUE);

  label105 = gtk_label_new ("<b>Interface</b>");
  gtk_widget_show (label105);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label105);
  gtk_label_set_use_markup (GTK_LABEL (label105), TRUE);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), frame3, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_NONE);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (frame3), hbox8);
  gtk_container_set_border_width (GTK_CONTAINER (hbox8), 12);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, "_Latin-1");
  gtk_widget_show (radiobutton1);
  gtk_box_pack_start (GTK_BOX (hbox8), radiobutton1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, "_UTF-8");
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (hbox8), radiobutton2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, "_HTML");
  gtk_widget_show (radiobutton3);
  gtk_box_pack_start (GTK_BOX (hbox8), radiobutton3, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  label106 = gtk_label_new ("<b>Files</b>");
  gtk_widget_show (label106);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label106);
  gtk_label_set_use_markup (GTK_LABEL (label106), TRUE);

  dialog_action_area1 = GTK_DIALOG (dialog_prefs)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  button20 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button20);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_prefs), button20, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (button20, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) dialog_prefs, "response",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dialog_prefs));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_prefs, dialog_prefs, "dialog_prefs");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_prefs, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog_prefs, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (dialog_prefs, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (dialog_prefs, showmenu, "showmenu");
  GLADE_HOOKUP_OBJECT (dialog_prefs, showstatusbar, "showstatusbar");
  GLADE_HOOKUP_OBJECT (dialog_prefs, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (dialog_prefs, usescrollbars, "usescrollbars");
  GLADE_HOOKUP_OBJECT (dialog_prefs, label105, "label105");
  GLADE_HOOKUP_OBJECT (dialog_prefs, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (dialog_prefs, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (dialog_prefs, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (dialog_prefs, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (dialog_prefs, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (dialog_prefs, label106, "label106");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_prefs, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog_prefs, button20, "button20");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_prefs, tooltips, "tooltips");

  gtk_widget_grab_focus (button20);
  gtk_widget_grab_default (button20);
  return dialog_prefs;
}

GtkWidget*
create_dialog_about (void)
{
  GtkWidget *dialog_about;
  GtkWidget *dialog_vbox2;
  GtkWidget *label117;
  GtkWidget *dialog_action_area2;
  GtkWidget *closebutton1;

  dialog_about = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_about), "About GtkGlk");

  dialog_vbox2 = GTK_DIALOG (dialog_about)->vbox;
  gtk_widget_show (dialog_vbox2);

  label117 = gtk_label_new ("GtkGlk 0.3 Copyright © 2003 Evin Robertson. \nNO WARRANTY.  Licensed under the GNU LGPL.\nPortions Copyright 1998-2000 Andrew Plotkin.\n\nImplements Glk 0.6.1 with Unicode extensions.\nSee <http://www.eblong.com/zarf/glk/> for details.\n");
  gtk_widget_show (label117);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), label117, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label117), 6, 6);

  dialog_action_area2 = GTK_DIALOG (dialog_about)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_about), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) dialog_about, "response",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dialog_about));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_about, dialog_about, "dialog_about");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_about, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog_about, label117, "label117");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_about, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog_about, closebutton1, "closebutton1");

  gtk_widget_grab_focus (closebutton1);
  gtk_widget_grab_default (closebutton1);
  return dialog_about;
}

GtkWidget*
create_dialog_gestalt (void)
{
  GtkWidget *dialog_gestalt;
  GtkWidget *dialog_vbox3;
  GtkWidget *hbox13;
  GtkWidget *label45;
  AtkRelationSet *tmp_relation_set;
  AtkRelationType tmp_relationship;
  AtkRelation *tmp_relation;
  AtkObject *label45_relation_targets[1];
  AtkObject *atko;
  GtkWidget *gestalt_claim_version;
  GtkWidget *enable_disable_pretend;
  GtkWidget *dialog_action_area3;
  GtkWidget *closebutton2;

  dialog_gestalt = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_gestalt), "Gestalt Preferences");

  dialog_vbox3 = GTK_DIALOG (dialog_gestalt)->vbox;
  gtk_widget_show (dialog_vbox3);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), hbox13, FALSE, TRUE, 0);

  label45 = gtk_label_new_with_mnemonic ("_Version");
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox13), label45, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label45), 0, 0.5);

  gestalt_claim_version = gtk_entry_new ();
  gtk_widget_show (gestalt_claim_version);
  gtk_box_pack_start (GTK_BOX (hbox13), gestalt_claim_version, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (gestalt_claim_version), "0.6.1");

  enable_disable_pretend = gtk_tree_view_new ();
  gtk_widget_show (enable_disable_pretend);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), enable_disable_pretend, TRUE, TRUE, 0);

  dialog_action_area3 = GTK_DIALOG (dialog_gestalt)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  closebutton2 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_gestalt), closebutton2, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton2, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) dialog_gestalt, "response",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dialog_gestalt));

  gtk_label_set_mnemonic_widget (GTK_LABEL (label45), gestalt_claim_version);

  atko = gtk_widget_get_accessible (label45);
  tmp_relation_set = atk_object_ref_relation_set (atko);
  label45_relation_targets[0] = gtk_widget_get_accessible (gestalt_claim_version);
  tmp_relationship = atk_relation_type_for_name ("label-for");
  tmp_relation = atk_relation_new (label45_relation_targets, 1, tmp_relationship);
  atk_relation_set_add (tmp_relation_set, tmp_relation);
  g_object_unref (G_OBJECT (tmp_relation));
  g_object_unref (G_OBJECT (tmp_relation_set));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_gestalt, dialog_gestalt, "dialog_gestalt");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_gestalt, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog_gestalt, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (dialog_gestalt, label45, "label45");
  GLADE_HOOKUP_OBJECT (dialog_gestalt, gestalt_claim_version, "gestalt_claim_version");
  GLADE_HOOKUP_OBJECT (dialog_gestalt, enable_disable_pretend, "enable_disable_pretend");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_gestalt, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog_gestalt, closebutton2, "closebutton2");

  gtk_widget_grab_focus (closebutton2);
  gtk_widget_grab_default (closebutton2);
  return dialog_gestalt;
}

GtkWidget*
create_dialog_styles (void)
{
  GtkWidget *dialog_styles;
  GtkWidget *dialog_vbox4;
  GtkWidget *table6;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label38;
  GtkWidget *label90;
  GtkWidget *label36;
  GtkWidget *label95;
  GtkWidget *important_Indentation;
  GtkWidget *important_ParaIndentation;
  GtkWidget *important_Size;
  GtkWidget *important_Weight;
  GtkWidget *important_Variant;
  GtkWidget *important_Oblique;
  GtkWidget *important_Underline;
  GtkWidget *important_TextColor;
  GtkWidget *important_BackColor;
  GtkWidget *important_ReverseColor;
  GtkWidget *important_Proportional;
  GtkWidget *hseparator14;
  GtkWidget *hseparator12;
  GtkWidget *hseparator11;
  GtkWidget *hseparator13;
  GtkWidget *label113;
  GtkWidget *label33;
  GtkWidget *hbox7;
  GtkWidget *label96;
  GtkWidget *style_justdefault;
  GSList *style_justdefault_group = NULL;
  GtkWidget *label37;
  GtkWidget *important_Direction;
  GtkWidget *important_Justification;
  GtkObject *style_Indentation_adj;
  GtkWidget *style_Indentation;
  GtkObject *style_ParaIndentation_adj;
  GtkWidget *style_ParaIndentation;
  GtkWidget *style_justleft;
  GtkWidget *style_justright;
  GtkWidget *style_justcenter;
  GtkWidget *style_justfill;
  GtkWidget *style_Direction;
  GtkWidget *style_family;
  GtkObject *style_Size_adj;
  GtkWidget *style_Size;
  GtkWidget *style_Weight;
  GtkWidget *alignment3;
  GtkWidget *hbox12;
  GtkWidget *image91;
  GtkWidget *label114;
  GtkWidget *style_Variant;
  GtkWidget *style_Oblique;
  GtkWidget *alignment1;
  GtkWidget *hbox10;
  GtkWidget *image1;
  GtkWidget *label111;
  GtkWidget *style_Underline;
  GtkWidget *alignment2;
  GtkWidget *hbox11;
  GtkWidget *image2;
  GtkWidget *label112;
  GtkWidget *style_BackColor;
  GtkWidget *style_TextColor;
  GtkWidget *style_ReverseColor;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview_styles;
  GtkWidget *scrolledwindow4;
  GtkWidget *preview;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancelbutton1;
  GtkWidget *applybutton1;
  GtkWidget *okbutton1;

  dialog_styles = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_styles), "Style Preferences");
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_styles), FALSE);

  dialog_vbox4 = GTK_DIALOG (dialog_styles)->vbox;
  gtk_widget_show (dialog_vbox4);

  table6 = gtk_table_new (18, 5, FALSE);
  gtk_widget_show (table6);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), table6, FALSE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table6), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table6), 6);

  label31 = gtk_label_new_with_mnemonic ("_Margins:");
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table6), label31, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  label32 = gtk_label_new_with_mnemonic ("_Indentation:");
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table6), label32, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  label34 = gtk_label_new_with_mnemonic ("Si_ze:");
  gtk_widget_show (label34);
  gtk_table_attach (GTK_TABLE (table6), label34, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label34), 0, 0.5);

  label35 = gtk_label_new_with_mnemonic ("_Weight:");
  gtk_widget_show (label35);
  gtk_table_attach (GTK_TABLE (table6), label35, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label35), 0, 0.5);

  label39 = gtk_label_new_with_mnemonic ("_BackColor:");
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table6), label39, 1, 2, 16, 17,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label39), 0, 0.5);

  label40 = gtk_label_new_with_mnemonic ("R_everse:");
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table6), label40, 1, 2, 17, 18,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);

  label38 = gtk_label_new_with_mnemonic ("_TextColor:");
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table6), label38, 1, 2, 15, 16,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  label90 = gtk_label_new_with_mnemonic ("_Underscore:");
  gtk_widget_show (label90);
  gtk_table_attach (GTK_TABLE (table6), label90, 1, 2, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label90), 0, 0.5);

  label36 = gtk_label_new_with_mnemonic ("_Slant:");
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table6), label36, 1, 2, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  label95 = gtk_label_new_with_mnemonic ("_Variant:");
  gtk_widget_show (label95);
  gtk_table_attach (GTK_TABLE (table6), label95, 1, 2, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label95), 0, 0.5);

  important_Indentation = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_Indentation);
  gtk_table_attach (GTK_TABLE (table6), important_Indentation, 4, 5, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_ParaIndentation = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_ParaIndentation);
  gtk_table_attach (GTK_TABLE (table6), important_ParaIndentation, 4, 5, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_Size = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_Size);
  gtk_table_attach (GTK_TABLE (table6), important_Size, 4, 5, 8, 9,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_Weight = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_Weight);
  gtk_table_attach (GTK_TABLE (table6), important_Weight, 4, 5, 9, 10,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_Variant = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_Variant);
  gtk_table_attach (GTK_TABLE (table6), important_Variant, 4, 5, 11, 12,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_Oblique = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_Oblique);
  gtk_table_attach (GTK_TABLE (table6), important_Oblique, 4, 5, 12, 13,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_Underline = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_Underline);
  gtk_table_attach (GTK_TABLE (table6), important_Underline, 4, 5, 13, 14,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_TextColor = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_TextColor);
  gtk_table_attach (GTK_TABLE (table6), important_TextColor, 4, 5, 15, 16,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_BackColor = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_BackColor);
  gtk_table_attach (GTK_TABLE (table6), important_BackColor, 4, 5, 16, 17,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_ReverseColor = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_ReverseColor);
  gtk_table_attach (GTK_TABLE (table6), important_ReverseColor, 4, 5, 17, 18,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_Proportional = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_Proportional);
  gtk_table_attach (GTK_TABLE (table6), important_Proportional, 4, 5, 7, 8,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator14 = gtk_hseparator_new ();
  gtk_widget_show (hseparator14);
  gtk_table_attach (GTK_TABLE (table6), hseparator14, 1, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hseparator12 = gtk_hseparator_new ();
  gtk_widget_show (hseparator12);
  gtk_table_attach (GTK_TABLE (table6), hseparator12, 1, 5, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hseparator11 = gtk_hseparator_new ();
  gtk_widget_show (hseparator11);
  gtk_table_attach (GTK_TABLE (table6), hseparator11, 1, 5, 14, 15,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hseparator13 = gtk_hseparator_new ();
  gtk_widget_show (hseparator13);
  gtk_table_attach (GTK_TABLE (table6), hseparator13, 1, 5, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label113 = gtk_label_new_with_mnemonic ("Directio_n:");
  gtk_widget_show (label113);
  gtk_table_attach (GTK_TABLE (table6), label113, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label113), 0, 0.5);

  label33 = gtk_label_new ("Justification:");
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table6), label33, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_table_attach (GTK_TABLE (table6), hbox7, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label96 = gtk_label_new ("");
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox7), label96, TRUE, TRUE, 0);

  style_justdefault = gtk_radio_button_new_with_mnemonic (NULL, "_Inherit");
  gtk_widget_show (style_justdefault);
  gtk_box_pack_start (GTK_BOX (hbox7), style_justdefault, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (style_justdefault), style_justdefault_group);
  style_justdefault_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (style_justdefault));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (style_justdefault), TRUE);

  label37 = gtk_label_new_with_mnemonic ("Famil_y:");
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table6), label37, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  important_Direction = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_Direction);
  gtk_table_attach (GTK_TABLE (table6), important_Direction, 4, 5, 5, 6,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  important_Justification = gtk_toggle_button_new_with_mnemonic ("Important");
  gtk_widget_show (important_Justification);
  gtk_table_attach (GTK_TABLE (table6), important_Justification, 4, 5, 3, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  style_Indentation_adj = gtk_adjustment_new (0, -100, 100, 1, 10, 10);
  style_Indentation = gtk_spin_button_new (GTK_ADJUSTMENT (style_Indentation_adj), 1, 0);
  gtk_widget_show (style_Indentation);
  gtk_table_attach (GTK_TABLE (table6), style_Indentation, 2, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (style_Indentation), TRUE);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (style_Indentation), TRUE);

  style_ParaIndentation_adj = gtk_adjustment_new (0, -100, 100, 1, 10, 10);
  style_ParaIndentation = gtk_spin_button_new (GTK_ADJUSTMENT (style_ParaIndentation_adj), 1, 0);
  gtk_widget_show (style_ParaIndentation);
  gtk_table_attach (GTK_TABLE (table6), style_ParaIndentation, 2, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (style_ParaIndentation), TRUE);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (style_ParaIndentation), TRUE);

  style_justleft = gtk_radio_button_new_with_mnemonic (NULL, "gtk-justify-left");
  gtk_button_set_use_stock (GTK_BUTTON (style_justleft), TRUE);
  gtk_widget_show (style_justleft);
  gtk_table_attach (GTK_TABLE (table6), style_justleft, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (style_justleft), style_justdefault_group);
  style_justdefault_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (style_justleft));

  style_justright = gtk_radio_button_new_with_mnemonic (NULL, "gtk-justify-right");
  gtk_button_set_use_stock (GTK_BUTTON (style_justright), TRUE);
  gtk_widget_show (style_justright);
  gtk_table_attach (GTK_TABLE (table6), style_justright, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (style_justright), style_justdefault_group);
  style_justdefault_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (style_justright));

  style_justcenter = gtk_radio_button_new_with_mnemonic (NULL, "gtk-justify-center");
  gtk_button_set_use_stock (GTK_BUTTON (style_justcenter), TRUE);
  gtk_widget_show (style_justcenter);
  gtk_table_attach (GTK_TABLE (table6), style_justcenter, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (style_justcenter), style_justdefault_group);
  style_justdefault_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (style_justcenter));

  style_justfill = gtk_radio_button_new_with_mnemonic (NULL, "gtk-justify-fill");
  gtk_button_set_use_stock (GTK_BUTTON (style_justfill), TRUE);
  gtk_widget_show (style_justfill);
  gtk_table_attach (GTK_TABLE (table6), style_justfill, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (style_justfill), style_justdefault_group);
  style_justdefault_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (style_justfill));

  style_Direction = gtk_check_button_new_with_mnemonic ("Right to Left");
  gtk_widget_show (style_Direction);
  gtk_table_attach (GTK_TABLE (table6), style_Direction, 2, 4, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  style_family = gtk_option_menu_new ();
  gtk_widget_show (style_family);
  gtk_table_attach (GTK_TABLE (table6), style_family, 2, 4, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  style_Size_adj = gtk_adjustment_new (0, -5, 5, 1, 1, 10);
  style_Size = gtk_spin_button_new (GTK_ADJUSTMENT (style_Size_adj), 1, 0);
  gtk_widget_show (style_Size);
  gtk_table_attach (GTK_TABLE (table6), style_Size, 2, 4, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (style_Size), TRUE);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (style_Size), TRUE);

  style_Weight = gtk_check_button_new ();
  gtk_widget_show (style_Weight);
  gtk_table_attach (GTK_TABLE (table6), style_Weight, 2, 4, 9, 10,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (style_Weight), alignment3);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox12);

  image91 = gtk_image_new_from_stock ("gtk-bold", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image91);
  gtk_box_pack_start (GTK_BOX (hbox12), image91, FALSE, FALSE, 0);

  label114 = gtk_label_new_with_mnemonic ("Bold");
  gtk_widget_show (label114);
  gtk_box_pack_start (GTK_BOX (hbox12), label114, FALSE, FALSE, 0);

  style_Variant = gtk_check_button_new_with_mnemonic ("Small Caps");
  gtk_widget_show (style_Variant);
  gtk_table_attach (GTK_TABLE (table6), style_Variant, 2, 4, 11, 12,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  style_Oblique = gtk_check_button_new ();
  gtk_widget_show (style_Oblique);
  gtk_table_attach (GTK_TABLE (table6), style_Oblique, 2, 4, 12, 13,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (style_Oblique), alignment1);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox10);

  image1 = gtk_image_new_from_stock ("gtk-italic", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox10), image1, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic ("Italic");
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox10), label111, FALSE, FALSE, 0);

  style_Underline = gtk_check_button_new ();
  gtk_widget_show (style_Underline);
  gtk_table_attach (GTK_TABLE (table6), style_Underline, 2, 4, 13, 14,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (style_Underline), alignment2);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox11);

  image2 = gtk_image_new_from_stock ("gtk-underline", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox11), image2, FALSE, FALSE, 0);

  label112 = gtk_label_new_with_mnemonic ("Underline");
  gtk_widget_show (label112);
  gtk_box_pack_start (GTK_BOX (hbox11), label112, FALSE, FALSE, 0);

  style_BackColor = gglk_colorpicker_new_glade ("style_BackColor", "Choose a Background Color", NULL, 0, 0);
  gtk_widget_show (style_BackColor);
  gtk_table_attach (GTK_TABLE (table6), style_BackColor, 2, 4, 16, 17,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  GTK_WIDGET_SET_FLAGS (style_BackColor, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (style_BackColor, GTK_CAN_DEFAULT);

  style_TextColor = gglk_colorpicker_new_glade ("style_TextColor", "Choose a Foreground Color", NULL, 0, 0);
  gtk_widget_show (style_TextColor);
  gtk_table_attach (GTK_TABLE (table6), style_TextColor, 2, 4, 15, 16,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  GTK_WIDGET_SET_FLAGS (style_TextColor, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (style_TextColor, GTK_CAN_DEFAULT);

  style_ReverseColor = gtk_check_button_new_with_mnemonic ("Inverse Color");
  gtk_widget_show (style_ReverseColor);
  gtk_table_attach (GTK_TABLE (table6), style_ReverseColor, 2, 4, 17, 18,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_table_attach (GTK_TABLE (table6), scrolledwindow5, 0, 1, 0, 18,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_ETCHED_IN);

  treeview_styles = gtk_tree_view_new ();
  gtk_widget_show (treeview_styles);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview_styles);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_ETCHED_IN);

  preview = gtk_text_view_new ();
  gtk_widget_show (preview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), preview);
  gtk_widget_set_size_request (preview, 0, -1);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (preview), GTK_WRAP_WORD);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (preview)),
	"The quick brown fox jumps over a lazy dog.\nGame style hints modify individual styles, which modify attributes set in \"All Styles.\"  Attributes marked \"Important\" are unaffected by unimportant modifications.", -1);

  dialog_action_area4 = GTK_DIALOG (dialog_styles)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_styles), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  applybutton1 = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (applybutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_styles), applybutton1, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (applybutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_styles), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label31), style_Indentation);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label32), style_ParaIndentation);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label34), style_Size);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label35), style_Weight);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label39), style_BackColor);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label40), style_ReverseColor);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label38), style_TextColor);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label90), style_Underline);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label36), style_Oblique);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label95), style_Variant);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label113), style_Direction);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label37), style_family);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_styles, dialog_styles, "dialog_styles");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_styles, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (dialog_styles, table6, "table6");
  GLADE_HOOKUP_OBJECT (dialog_styles, label31, "label31");
  GLADE_HOOKUP_OBJECT (dialog_styles, label32, "label32");
  GLADE_HOOKUP_OBJECT (dialog_styles, label34, "label34");
  GLADE_HOOKUP_OBJECT (dialog_styles, label35, "label35");
  GLADE_HOOKUP_OBJECT (dialog_styles, label39, "label39");
  GLADE_HOOKUP_OBJECT (dialog_styles, label40, "label40");
  GLADE_HOOKUP_OBJECT (dialog_styles, label38, "label38");
  GLADE_HOOKUP_OBJECT (dialog_styles, label90, "label90");
  GLADE_HOOKUP_OBJECT (dialog_styles, label36, "label36");
  GLADE_HOOKUP_OBJECT (dialog_styles, label95, "label95");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_Indentation, "important_Indentation");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_ParaIndentation, "important_ParaIndentation");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_Size, "important_Size");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_Weight, "important_Weight");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_Variant, "important_Variant");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_Oblique, "important_Oblique");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_Underline, "important_Underline");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_TextColor, "important_TextColor");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_BackColor, "important_BackColor");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_ReverseColor, "important_ReverseColor");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_Proportional, "important_Proportional");
  GLADE_HOOKUP_OBJECT (dialog_styles, hseparator14, "hseparator14");
  GLADE_HOOKUP_OBJECT (dialog_styles, hseparator12, "hseparator12");
  GLADE_HOOKUP_OBJECT (dialog_styles, hseparator11, "hseparator11");
  GLADE_HOOKUP_OBJECT (dialog_styles, hseparator13, "hseparator13");
  GLADE_HOOKUP_OBJECT (dialog_styles, label113, "label113");
  GLADE_HOOKUP_OBJECT (dialog_styles, label33, "label33");
  GLADE_HOOKUP_OBJECT (dialog_styles, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (dialog_styles, label96, "label96");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_justdefault, "style_justdefault");
  GLADE_HOOKUP_OBJECT (dialog_styles, label37, "label37");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_Direction, "important_Direction");
  GLADE_HOOKUP_OBJECT (dialog_styles, important_Justification, "important_Justification");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_Indentation, "style_Indentation");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_ParaIndentation, "style_ParaIndentation");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_justleft, "style_justleft");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_justright, "style_justright");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_justcenter, "style_justcenter");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_justfill, "style_justfill");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_Direction, "style_Direction");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_family, "style_family");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_Size, "style_Size");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_Weight, "style_Weight");
  GLADE_HOOKUP_OBJECT (dialog_styles, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (dialog_styles, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (dialog_styles, image91, "image91");
  GLADE_HOOKUP_OBJECT (dialog_styles, label114, "label114");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_Variant, "style_Variant");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_Oblique, "style_Oblique");
  GLADE_HOOKUP_OBJECT (dialog_styles, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (dialog_styles, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (dialog_styles, image1, "image1");
  GLADE_HOOKUP_OBJECT (dialog_styles, label111, "label111");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_Underline, "style_Underline");
  GLADE_HOOKUP_OBJECT (dialog_styles, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (dialog_styles, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (dialog_styles, image2, "image2");
  GLADE_HOOKUP_OBJECT (dialog_styles, label112, "label112");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_BackColor, "style_BackColor");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_TextColor, "style_TextColor");
  GLADE_HOOKUP_OBJECT (dialog_styles, style_ReverseColor, "style_ReverseColor");
  GLADE_HOOKUP_OBJECT (dialog_styles, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (dialog_styles, treeview_styles, "treeview_styles");
  GLADE_HOOKUP_OBJECT (dialog_styles, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (dialog_styles, preview, "preview");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_styles, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (dialog_styles, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog_styles, applybutton1, "applybutton1");
  GLADE_HOOKUP_OBJECT (dialog_styles, okbutton1, "okbutton1");

  return dialog_styles;
}

